Repository runtimeverification/pyk, pull requests merged in 2024-03, with the labels that each got.

#937 Fix failure info not being set
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/implies.py
  src/pyk/proof/proof.py
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_imp.py
Labels: automerge, bug

#938 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/tests/integration/k-files/cell-map.k
  src/tests/integration/k-files/goto.k
  src/tests/integration/k-files/imp.k
  src/tests/integration/k-files/mini-kevm.k
  src/tests/integration/k-files/multiple-definitions.k
  src/tests/integration/k-files/simple-proofs.k
  src/tests/integration/k-files/smt.k
  src/tests/integration/k-files/unparsing.k
  src/tests/integration/kore/test_kore_client.py
Labels: automerge

#940 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#943 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#933 Add `to_claim` method to `RefutationProof`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/__init__.py
  src/pyk/cterm/cterm.py
  src/pyk/kast/manip.py
  src/pyk/kcfg/kcfg.py
  src/pyk/ktool/kprove.py
  src/pyk/proof/implies.py
  src/tests/integration/proof/test_refute_node.py
  src/tests/unit/test_cterm.py
Labels: automerge

#939 Maintaining information on nodes being terminal
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/tests/integration/k-files/simple-proofs-spec.k
  src/tests/integration/k-files/simple-proofs.k
  src/tests/integration/proof/test_simple.py
Labels: automerge, bug

#941 Added function to format execution time
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/tests/unit/test_proof.py
Labels: automerge

#950 Change `Lexical` from `ProductionLike` to `ProductionItem`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer_parser.py
  src/pyk/kast/outer_syntax.py
  src/tests/unit/kast/test_outer_parser.py
Labels: automerge

#952 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#951 Fix failure info not being set in advance_proof on done proof
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/proof.py
  src/tests/integration/proof/test_imp.py
Labels: automerge, bug

#916 Improve default argument handling
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__main__.py
  src/pyk/cli/args.py
  src/pyk/cli/cli.py
  src/pyk/cli/pyk.py
  src/pyk/cli/utils.py
  src/pyk/kdist/__main__.py
Labels: automerge

#953 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#955 Fix default boolean options always going to False
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cli/args.py
  src/pyk/kdist/__main__.py
Labels: automerge

#956 Revert changes to options
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__main__.py
  src/pyk/cli/args.py
  src/pyk/cli/cli.py
  src/pyk/cli/pyk.py
  src/pyk/cli/utils.py
  src/pyk/kdist/__main__.py
Labels: automerge

#948 Add RPC based prover to KProve interface
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__main__.py
  src/pyk/cterm/__init__.py
  src/pyk/cterm/symbolic.py
  src/pyk/ktool/kprove.py
  src/pyk/proof/__init__.py
  src/tests/integration/kprove/test_prove_cterm.py
  src/tests/integration/ktool/__init__.py
  src/tests/integration/ktool/test_imp.py
  src/tests/integration/test_pyk.py
Labels: automerge

#962 Set `failure_info` if `fail_fast` is on
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/proof.py
  src/tests/integration/proof/test_imp.py
Labels: automerge

#922 cache prior loops discovered in bmc
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
Labels: automerge

#967 Options improvements retry
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__main__.py
  src/pyk/cli/args.py
  src/pyk/cli/cli.py
  src/pyk/cli/pyk.py
  src/pyk/cli/utils.py
  src/pyk/kdist/__main__.py
Labels: automerge

#966 Generate subsort axioms
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#971 Generate associativity axioms
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer.py
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#969 Refactor `Proof.status`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/implies.py
  src/pyk/proof/proof.py
  src/pyk/proof/reachability.py
Labels: automerge

#958 pyk cli for kompiling and running proofs with rpc booster
  .github/workflows/test-pr.yml
  Makefile
  docs/conf.py
  package/version
  pyproject.toml
  regression-new/Makefile
  regression-new/include/ktest-group.mak
  regression-new/include/ktest.mak
  regression-new/kprove-haskell/Makefile
  regression-new/kprove-haskell/test-fail-spec.k
  regression-new/kprove-haskell/test-fail-spec.k.out
  regression-new/kprove-haskell/test-spec.k
  regression-new/kprove-haskell/test-spec.k.out
  regression-new/kprove-haskell/verif.k
  src/pyk/__main__.py
  src/pyk/cli/args.py
  src/pyk/ktool/kompile.py
  src/pyk/ktool/kprove.py
Labels: automerge

#970 TUI.py: add Status component
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/style.css
  src/pyk/kcfg/tui.py
  src/pyk/proof/tui.py
Labels: automerge, enhancement, tui

#977 Generate `idem`, `unit` and `functional` axioms
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/att.py
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#973 Add command `pyk run` and tests from `regression-new`
  docs/conf.py
  package/version
  pyproject.toml
  regression-new/include/ktest-group.mak
  regression-new/include/ktest.mak
  regression-new/withConfig/1.test
  regression-new/withConfig/1.test.out
  regression-new/withConfig/2.test
  regression-new/withConfig/2.test.out
  regression-new/withConfig/3.test
  regression-new/withConfig/3.test.out
  regression-new/withConfig/4.test
  regression-new/withConfig/4.test.out
  regression-new/withConfig/5.test
  regression-new/withConfig/5.test.out
  regression-new/withConfig/Makefile
  regression-new/withConfig/test.k
  src/pyk/__main__.py
  src/pyk/cli/args.py
  src/pyk/kast/pretty.py
  src/pyk/ktool/krun.py
  src/tests/integration/cterm/test_multiple_definitions.py
  src/tests/integration/cterm/test_simple.py
  src/tests/integration/k-files/imp-unproveable-spec.k.expected
  src/tests/integration/proof/test_cell_map.py
  src/tests/integration/proof/test_imp.py
  src/tests/integration/test-data/pyk-rpc-print/imp-execute-request.pretty.golden
  src/tests/integration/test-data/pyk-rpc-print/imp-simplify-request.pretty.golden
  src/tests/integration/test-data/pyk-rpc-print/imp-simplify-response.pretty.golden
  src/tests/integration/test_kprint.py
Labels: automerge

#979 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/pyk/kllvm/ast.py
  src/pyk/kllvm/convert.py
  src/pyk/kore/prelude.py
  src/tests/integration/konvert/test_simple_proofs.py
Labels: automerge

#972 pretty print kore pattern in `SmtSolverError`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/symbolic.py
  src/pyk/kore/rpc.py
  src/tests/unit/kore/test_client.py
Labels: automerge, enhancement

#983 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#976 Options classes
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__main__.py
  src/pyk/cli/args.py
  src/pyk/cli/cli.py
  src/pyk/cli/pyk.py
  src/pyk/ktool/kprove.py
  src/tests/integration/ktool/test_imp.py
Labels: automerge

#978 Generate no-confusion axioms
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#985 Optimize CI load
  .github/actions/setup-env/action.yml
  .github/workflows/test-pr.yml
  docs/conf.py
  package/version
  pyproject.toml
Labels: automerge

#987 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#984 Generate no-junk axioms
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/att.py
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#990 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#991 Add class `POSet`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer.py
  src/pyk/konvert/_module_to_kore.py
  src/pyk/kore/kompiled.py
  src/pyk/utils.py
  src/tests/unit/test_utils.py
Labels: automerge

#994 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#999 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1003 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  regression-new/issue-567/Makefile
  regression-new/issue-567/test.k
  regression-new/prelude-warnings/test.k
  src/pyk/__init__.py
Labels: automerge

#1000 Generate overload axioms
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/att.py
  src/pyk/kast/outer.py
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#1007 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1016 Increase test timeout values
  .github/workflows/test-pr.yml
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/testing/_kompiler.py
Labels: automerge

#1015 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/pyk/testing/__init__.py
  src/tests/integration/kore/test_kore_client.py
Labels: automerge

#1017 Fine-tune CI tests
  .github/actions/setup-env/action.yml
  .github/workflows/test-pr.yml
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/testing/_kompiler.py
  src/tests/integration/proof/test_imp.py
Labels: automerge

#1004 Extend `_module_to_kore` test suite
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/konvert/_module_to_kore.py
  src/tests/integration/konvert/test_module_to_kore.py
  src/tests/integration/test-data/module-to-kore/anywhere.k
  src/tests/integration/test-data/module-to-kore/empty.k
  src/tests/integration/test-data/module-to-kore/format.k
  src/tests/integration/test-data/module-to-kore/hook.k
  src/tests/integration/test-data/module-to-kore/overload.k
Labels: automerge

#1010 Generate attributes `priorities`, `left` and `right`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/att.py
  src/pyk/kast/outer.py
  src/pyk/konvert/_module_to_kore.py
  src/tests/integration/konvert/test_module_to_kore.py
Labels: automerge

#1020 Update `poetry.lock`
  docs/conf.py
  flake.nix
  package/version
  poetry.lock
  pyproject.toml
  src/pyk/cli/pyk.py
  src/pyk/kast/att.py
  src/pyk/kast/inner.py
  src/pyk/kast/kast.py
  src/pyk/kast/markdown.py
  src/pyk/kast/outer.py
  src/pyk/kast/outer_syntax.py
  src/pyk/kbuild/project.py
  src/pyk/kcfg/kcfg.py
  src/pyk/kcfg/semantics.py
  src/pyk/kcfg/store.py
  src/pyk/kdist/_kdist.py
  src/pyk/kdist/api.py
  src/pyk/kllvm/convert.py
  src/pyk/kore/match.py
  src/pyk/kore/rpc.py
  src/pyk/kore/syntax.py
  src/pyk/krepl/repl.py
  src/pyk/ktool/kompile.py
  src/pyk/proof/proof.py
  src/pyk/proof/reachability.py
  src/pyk/testing/_kompiler.py
  src/pyk/utils.py
  src/tests/unit/kast/test_kast.py
  src/tests/unit/test_proof.py
Labels: automerge

#1021 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1013 Computing substitutions when creating `Split` nodes
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/inner.py
  src/pyk/kcfg/kcfg.py
  src/pyk/proof/reachability.py
  src/tests/unit/test_kcfg.py
Labels: automerge, enhancement

#1022 Make KAST preprocessing pipeline explicit in `_module_to_kore`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#1023 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1027 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1029 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1030 Fix `AddDomainValueAtts`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/konvert/_module_to_kore.py
  src/tests/integration/konvert/test_module_to_kore.py
Labels: automerge

#1018 Allow loading single kcfg nodes
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/kcfg.py
Labels: automerge

#1031 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1026 Refactor no_cell_rewrite_to_dots
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/symbolic.py
  src/pyk/kast/manip.py
  src/pyk/kcfg/explore.py
  src/tests/unit/test_kcfg.py
Labels: automerge, bug

#1033 Minimizing substitution printing in `Split` nodes
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/show.py
Labels: automerge, enhancement

#1036 Add method `map_sentences` to `KFlatModule`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer.py
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#1037 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1039 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  regression-new/checkWarns/singletonOverload.k.out
  src/pyk/__init__.py
Labels: automerge

#1034 Use `SIGTERM` to stop server
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kore/rpc.py
Labels: automerge

#1025 SMT solver error timeout message added
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/symbolic.py
Labels: automerge, enhancement

#1041 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1042 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1048 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1002 Node attribute storage in nodes
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/exploration.py
  src/pyk/kcfg/explore.py
  src/pyk/kcfg/kcfg.py
  src/pyk/kcfg/store.py
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_cell_map.py
  src/tests/integration/proof/test_imp.py
  src/tests/integration/proof/test_mini_kevm.py
  src/tests/unit/test_kcfg.py
  src/tests/unit/test_proof.py
Labels: automerge, enhancement

#1047 Pass --debug to kompile in kbuild
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kbuild/__main__.py
  src/pyk/kbuild/kbuild.py
Labels: automerge

#1049 Remove dest from the --debug arg
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kbuild/__main__.py
Labels: automerge
