Repository runtimeverification/pyk, pull requests merged in 2024-02, with the labels that each got.

#854 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#856 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#855 Remove usages of `kore` attribute
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/profiling/test-data/domains.md
Labels: automerge

#857 Print parseable rules from KCFGShow
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/show.py
Labels: automerge

#859 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#864 Modify outer lexer to admit dots in attribute keys
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer_lexer.py
  src/tests/unit/test-data/outer-lexer/attr-key-with-dots.test
Labels: automerge

#866 Fix claim selection process for unlabeled claims
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/ktool/kprove.py
  src/tests/integration/k-files/multi-claim-spec.k
  src/tests/integration/kprove/test_get_claims.py
Labels: automerge

#863 Move node refutation functionality from APRProver to APRProof
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_refute_node.py
Labels: automerge

#865 Add `module_name` method for method name processing
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/tests/unit/test_proof.py
Labels: automerge

#861 Implement KAST-to-KORE conversion of symbol declarations
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/kast.py
  src/pyk/konvert.py
  src/tests/integration/test_konvert.py
Labels: automerge

#874 Change log level for `UNIQUE_ID` clash between sentences
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer.py
Labels: automerge

#877 Fix bugs in node refutation functionality
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/pyk/proof/show.py
Labels: automerge

#876 Add timeouts to CI pipeline
  .github/workflows/test-pr.yml
  docs/conf.py
  package/version
  poetry.lock
  pyproject.toml
Labels: automerge

#869 Warn on bounded nodes
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
Labels: automerge

#878 Overhaul ImpliesProof class hierarchy
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/prelude/ml.py
  src/pyk/proof/__init__.py
  src/pyk/proof/equality.py
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_equality_proof.py
  src/tests/integration/proof/test_refute_node.py
Labels: automerge

#860 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/pyk/kore/prelude.py
  src/tests/integration/k-files/multiple-definitions.k
  src/tests/integration/kllvm/test_internal_term.py
  src/tests/integration/test-data/pyk-rpc-kast/imp-execute-request.json
  src/tests/integration/test-data/pyk-rpc-kast/imp-simplify-request.json
  src/tests/integration/test-data/pyk-rpc-print/imp-execute-request.json
  src/tests/integration/test-data/pyk-rpc-print/imp-simplify-request.json
  src/tests/integration/test-data/pyk-rpc-print/imp-simplify-response.json
  src/tests/integration/test_kprint.py
  src/tests/integration/test_krun.py
  src/tests/unit/test-data/munge-tests
Labels: automerge

#880 Add test for `KProduction.label`
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/integration/k-files/klabel.k
  src/tests/integration/test_kompile.py
Labels: automerge

#888 Allow universal binding in ImpliesProof
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/explore.py
  src/pyk/proof/__init__.py
  src/pyk/proof/implies.py
  src/pyk/proof/proof.py
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_implies_proof.py
  src/tests/integration/proof/test_refute_node.py
  src/tests/unit/test_proof.py
Labels: automerge

#884 Adds new tests for node refutation
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/integration/proof/test_refute_node.py
Labels: automerge

#881 Added proof execution time to APRProof
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
Labels: automerge

#889 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#890 Change `KAtt` key type from `str` to `AttKey`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/coverage.py
  src/pyk/cterm.py
  src/pyk/kast/__init__.py
  src/pyk/kast/kast.py
  src/pyk/kast/manip.py
  src/pyk/kast/outer.py
  src/pyk/kast/pretty.py
  src/pyk/konvert/_kast_to_kore.py
  src/pyk/konvert/_module_to_kore.py
  src/pyk/kore_exec_covr/__main__.py
  src/pyk/kore_exec_covr/kore_exec_covr.py
  src/pyk/ktool/kprove.py
  src/tests/integration/konvert/test_simple_proofs.py
  src/tests/integration/kprove/test_prove_claim_with_lemmas.py
  src/tests/integration/test_parse_kast.py
  src/tests/unit/test_cterm.py
Labels: automerge

#892 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#893 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#894 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#898 Fix comment
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/konvert/_module_to_kore.py
Labels: automerge

#895 Make `AttKey` generic
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/coverage.py
  src/pyk/cterm.py
  src/pyk/kast/__init__.py
  src/pyk/kast/kast.py
  src/pyk/kast/manip.py
  src/pyk/kast/outer.py
  src/pyk/kast/pretty.py
  src/pyk/konvert/_kast_to_kore.py
  src/pyk/konvert/_module_to_kore.py
  src/pyk/kore_exec_covr/__main__.py
  src/pyk/kore_exec_covr/kore_exec_covr.py
  src/pyk/ktool/kprove.py
  src/tests/integration/konvert/test_simple_proofs.py
  src/tests/integration/kprove/test_prove_claim_with_lemmas.py
  src/tests/integration/test_kompile.py
  src/tests/integration/test_parse_kast.py
  src/tests/unit/test_cterm.py
Labels: automerge

#897 Extract module `att`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm.py
  src/pyk/kast/__init__.py
  src/pyk/kast/att.py
  src/pyk/kast/kast.py
  src/pyk/kast/manip.py
  src/pyk/kast/outer.py
  src/pyk/kast/pretty.py
  src/pyk/kcfg/kcfg.py
  src/tests/integration/kprove/test_emit_json_spec.py
Labels: automerge

#899 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#900 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#902 Replace `.` by `.K` in K input
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/integration/k-files/bytes-rewrite.k
  src/tests/integration/k-files/goto.k
  src/tests/integration/k-files/imp-simple-spec.k
  src/tests/integration/k-files/imp.k
  src/tests/integration/k-files/looping-spec.k
  src/tests/integration/k-files/return-code.k
  src/tests/integration/k-files/string-rewrite.k
  src/tests/integration/test_kprint.py
  src/tests/profiling/test-data/domains.md
Labels: automerge

#908 Added execution time to APRSummary
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/tests/unit/test_proof.py
Labels: automerge

#909 Move kcfg commit logic to KCFG class
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/explore.py
  src/pyk/kcfg/kcfg.py
  src/pyk/proof/reachability.py
Labels: automerge, enhancement

#904 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/pyk/konvert/_kore_to_kast.py
  src/pyk/kore/prelude.py
  src/tests/integration/kore/test_tools.py
  src/tests/integration/test_konvert.py
Labels: automerge

#910 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#921 Normal runners
  .github/workflows/test-pr.yml
  Dockerfile
  docs/conf.py
  package/version
  pyproject.toml
Labels: automerge

#915 Split out CTerm manipulation functionalities of KCFGExplore
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/__init__.py
  src/pyk/cterm/symbolic.py
  src/pyk/kcfg/explore.py
  src/pyk/proof/implies.py
  src/pyk/proof/reachability.py
  src/pyk/testing/__init__.py
  src/pyk/testing/_kompiler.py
  src/tests/integration/cterm/__init__.py
  src/tests/integration/cterm/test_multiple_definitions.py
  src/tests/integration/cterm/test_simple.py
  src/tests/integration/proof/test_cell_map.py
  src/tests/integration/proof/test_imp.py
  src/tests/integration/proof/test_mini_kevm.py
Labels: automerge

#907 Change nullary attribute value from `''` to `None`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/__init__.py
  src/pyk/kast/att.py
  src/pyk/konvert/_module_to_kore.py
  src/tests/integration/kprove/test_prove_claim_with_lemmas.py
  src/tests/integration/test_konvert.py
  src/tests/unit/kast/test_att.py
Labels: automerge

#923 Add `SmtSolverError`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kore/rpc.py
  src/tests/unit/kore/test_client.py
Labels: automerge

#924 Explicit result type for CTermSymbolic.implies
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/symbolic.py
  src/pyk/kcfg/explore.py
  src/pyk/proof/implies.py
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_imp.py
Labels: automerge

#926 Several small KCFG and CTermSymbolic class refactors/cleanups
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/symbolic.py
  src/pyk/kast/manip.py
  src/pyk/kcfg/kcfg.py
  src/tests/unit/test_kcfg.py
Labels: automerge

#930 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#928 Remove KPrint object from KCFGExplore
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/explore.py
  src/pyk/proof/implies.py
  src/pyk/proof/reachability.py
  src/pyk/testing/_kompiler.py
  src/tests/integration/proof/test_cell_map.py
  src/tests/integration/proof/test_goto.py
  src/tests/integration/proof/test_imp.py
  src/tests/integration/proof/test_implies_proof.py
  src/tests/integration/proof/test_mini_kevm.py
  src/tests/integration/proof/test_non_det.py
Labels: automerge

#901 Drop duplicate tokens in outer syntax
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer_lexer.py
  src/pyk/kast/outer_parser.py
  src/tests/profiling/test-data/domains.md
  src/tests/unit/kast/test_outer_parser.py
  src/tests/unit/test-data/outer-lexer/domains-00.test
  src/tests/unit/test-data/outer-lexer/domains-02-map.test
  src/tests/unit/test-data/outer-lexer/domains-03-rangemap.test
  src/tests/unit/test-data/outer-lexer/domains-11-k.test
  src/tests/unit/test-data/outer-lexer/syntax-priority.test
Labels: automerge, outer-parsing

#871 Add tests for `add-module` with hash as module name
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/integration/kore/test_kore_client.py
Labels: automerge

#903 Separate execution of proof steps from modification of proof state
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/explore.py
  src/pyk/proof/implies.py
  src/pyk/proof/proof.py
  src/pyk/proof/reachability.py
Labels: automerge, enhancement

#931 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#934 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/tests/integration/test_konvert.py
Labels: automerge

#936 Subsumption checking fix
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
Labels: automerge, bug
