Repository runtimeverification/pyk, pull requests merged in 2024-04, with the labels that each got.

#1055 Fix `SmtSolverError`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kore/rpc.py
  src/tests/unit/kore/test_client.py
Labels: automerge

#1028 Adjust overload axiom generation
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer.py
  src/pyk/konvert/_module_to_kore.py
  src/tests/integration/test-data/module-to-kore/overload.k
Labels: automerge

#1046 Fix `as_subsort`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer.py
  src/tests/integration/test_kompile.py
Labels: automerge

#1009 Further KCFG-to-KCFG transformations
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/cterm/cterm.py
  src/pyk/kast/manip.py
  src/pyk/kcfg/kcfg.py
  src/tests/unit/test_kcfg.py
  src/tests/unit/test_proof.py
Labels: automerge, enhancement, cse

#1014 Add JSON-RPC server to pyk
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/rpc/rpc.py
  src/tests/integration/test_json_rpc.py
Labels: automerge, enhancement

#1057 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1059 Minimization algorithm correction
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kcfg/kcfg.py
  src/tests/unit/test_kcfg.py
Labels: automerge, bug

#1058 Enable Booster in all `KoreClientTest` subclasses
  .github/workflows/test-pr.yml
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/integration/ktool/test_imp.py
  src/tests/integration/proof/test_imp.py
  src/tests/integration/proof/test_mini_kevm.py
  src/tests/integration/proof/test_non_det.py
Labels: automerge

#1060 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1061 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1062 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1063 Use total function for variable lookup in `IMP`
  docs/conf.py
  package/version
  pyproject.toml
  src/tests/integration/test-data/k-files/imp.k
Labels: automerge

#1064 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1067 Only allow letters as first character in `_modname`
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kast/outer_lexer.py
  src/tests/unit/kast/test_outer_lexer.py
Labels: automerge

#1068 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
Labels: automerge

#1066 Allowing multiple constraints in splits preceding nodes to be refuted
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/proof/reachability.py
  src/tests/integration/proof/test_refute_node.py
  src/tests/integration/test-data/k-files/refute-node-spec.k
Labels: automerge, enhancement

#1070 Update dependency: deps/k_release
  deps/k_release
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/__init__.py
  src/pyk/konvert/_module_to_kore.py
  src/tests/integration/proof/test_mini_kevm.py
Labels: automerge

#942 Process branch `rule-id` and condition from `kore-rpc` response
  docs/conf.py
  package/version
  pyproject.toml
  src/pyk/kore/manip.py
  src/pyk/kore/prelude.py
  src/pyk/kore/rpc.py
  src/tests/integration/kore/test_kore_client.py
  src/tests/unit/kore/test_client.py
  src/tests/unit/kore/test_manip.py
Labels: automerge
